name: "turbo_cache_server_otel"

services:
  s3_bucket:
    image: minio/minio:RELEASE.2025-02-18T16-25-55Z@sha256:1df91be8d6a6146001cd6be2569a12785a8ece583b511f56ebed08f1e65d3611
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    volumes:
      - s3_data:/data
    command: server /data --console-address ":9001"

  # Observability
  collector:
    image: otel/opentelemetry-collector:0.146.1@sha256:23f75833cfcf0ebdde9b2e1ba41616b9092294af6947f2feea1b4ebc393030f5
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317" # OTELP GRPC
      - "4318:4318" # OTELP HTTP

  prometheus:
    image: prom/prometheus:v3.10.0@sha256:4a61322ac1103a0e3aea2a61ef1718422a48fa046441f299d71e660a3bc71ae9
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-otlp-receiver
    ports:
      - "9090:9090"

  jaeger:
    image: jaegertracing/jaeger:2.15.1@sha256:a7dd965687d45507072676db81e6903706ba334dfc92f0c248125cfd9a70c483
    ports:
      - "4317" # OTELP GRPC
      - "4318" # OTELP HTTP
      - "16686:16686" # Jaeger UI

volumes:
  s3_data:
  
